import type { Metadata } from 'next';
import { Bebas_Neue, Merriweather_Sans } from 'next/font/google';

import './globals.css';
import ViewCanvas from '@/components/ViewCanvas';

const bebasNeue = Bebas_Neue({
  variable: '--font-bebas-neue',
  weight: '400',
  subsets: ['latin'],
});

const merriweatherSans = Merriweather_Sans({
  variable: '--font-merriweather-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Overdrive Energy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bebasNeue.variable} ${merriweatherSans.variable} antialiased`}>
        <ViewCanvas />
        {children}
      </body>
    </html>
  );
}
